### ISSUE TITLE
While loop

### ISSUE THREAD

**Issue by Yasintje** [larsjarred9/snoepkoning-webapp#1]
https://github.com/larsjarred9/SnoepKoning/blob/16b34c61e765a5ee4d6611aa81fae3db9401d1f3/samenstellen.php#L62

You could have just used:
<?php 
    while ($stmt->fetch()) {
?>
// Some html (+ you cane use your PHP variables in here)
<?php
}
?>

**Comment by larsjarred9** [comment]
Thank you for notifying me. This will not be improved.
